### ISSUE TITLE
Suggestion: Lower opacity of entire Controls panel unless hovered/active 

### ISSUE THREAD

**Issue by oaustegard** [iangilman/trailers#2]
Get that turn-down-the-lights effect by making the controls partially opaque when the user is not actively engaging with them

**Comment by iangilman** [comment]
Yes! That is an excellent idea.

The controls used to hover over the video and go away entirely why not in use, but YouTube made me change it so they don't overlap the video at all… it didn't occur to me to keep the dimming as I did so.

Thank you for the feature request! I wonder if you're the only other person besides me who uses this little toy… I'm glad I'm not the only one! Though of course if you make something you yourself will use, at least you have one customer 😉

**Comment by oaustegard** [comment]
Yup 😀 that's my own take on my latest project: https://github.com/oaustegard/bookmarklets

**Comment by iangilman** [comment]
Nice! 😊

**Comment by iangilman** [comment]
@oaustegard Okay, fixed! Give it a try and see what you think :)

**Comment by oaustegard** [comment]
Better! Thanks!
